export const GET_INQUIRIES = 'ADD_INQUIRIES';
export const DELETE_INQUIRY = 'DELETE_INQUIRy';
export const FILTER_INQUIRIES = 'FILTER_INQUIRIES';;
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_SHOWMESSAGE = 'SET_SHOWMESSAGE';
export const CLEAR_SET_MESSAGE = 'CLEAR_SET_MESSAGE';
export const SET_REPLY_CLICKED = 'SET_REPLY_CLICKED';
export const CLEAR_REPLY = 'CLEAR_REPLY';
export const ADD_INQUIRY = 'ADD_INQUIRY';
export const SET_SERVICE_TYPE = 'SET_SERVICE_TYPE';




